global_config_params:
 base_url: https://testrail.sea.corp.expecn.com
 user: sbarylau
 password: 0Ze\xC9]W\x8D\xD6\xCF\x9A\xA0`\n#(I
 secret_key: secret

automation_section_params:
 phone:
  project_id: 25
  suite_id: 1586
  automation_section_id: 24621
 tablet:
  project_id: 25
  suite_id: 1573
  automation_section_id: 19381





